from .solution import infer_mrna_from_protein


def test_infer_mrna_from_protein():
    assert infer_mrna_from_protein(protein="MA") == 12


def test_example():
    protein = (
        "MQQDAGVWVYHTKVYKAQHPNAQNERLFASRWTLFIQYPEHSAWPGFEYWIWPHWIDDADYCTEARQLDAPQSWKYWKIFRRESNGTMWEDASIEKQDQCNT"
        "DHFKACYEQFGNTNDQEFDHEGWNFLKIWDNWDKGTRRLGPKTAWELCRPTKWVQGRRWVYENIFCNMQLNVMGILIPTFRAKHVIYGWCKDSTFSTMQEIT"
        "LYVGRMWFMRINAYKLMWYVDKWDYVVWIQFIWAWWLVSKLPVQWYNKARGLALMVAQQIYQRIDQWEWQAKEKFMKACCPMTLSEGQDPKQAGHGRIFIYV"
        "ICFIWRVMVFGTEYTFEYGVKYTRRTRNDHHGYRHEIWYKDRDNSAWDCTQEPEDQAWTCCMFNTGKSVSLNIGLTVSQHNNAMFEFGWLEVTYRAEDFFLG"
        "AEWRRILAIIKELEGVCGKFGRAGQGRVSDALWGMNQLKRCQDCYTYWNTMCLGEVETFPRVSNAQPKDCLAHDMCKILYNYVYFLCKNRYHDSGPNEFIRW"
        "IKQIEILCHNYIMHITMLQYLEKQMSPPGDYEKHFHVANRCPQICAEMFKGFTGHGFSWPIAEFPPDPTLHFLTAGDYWAREPPSHFPVFDSYPETSWLPYM"
        "WSKEHRLTSAIFRHCDWWAHPGYINQMMCEDVIGQSSDVRLDWGAVSSFQYKEVHEPDWWGDAYNPFWIKIETACAMANTNMETVNMEAPKGLEQHATVYGC"
        "RDDVAREHGCMLRRKIMLDSDKDGGYEEHSVHHVGVREQKFRMWPPWNHAWRYHTTQCSRLHISHFGFYKDSSMQTQAMKFTWDHKPRWVGPENHSEDHKAP"
        "KQTNGAMWNNQMAEVFKDMGRVHRYPGEQRSQERDGDHFSPCMDCGFWCMVNGGEATPCVALIMSMFVKRLPTRSKIKIKYTDFQEVAREFEHYKYVSSIGI"
        "NWYMANLHDRIAANFECILTCWAKHIWLSGLQEGLLYTMWKHAQQGSEEFQDVQFGGVGTGGEHPIQNHGSYRNNLTGA"
    )
    assert infer_mrna_from_protein(protein) == 849408
